name: Documentation Generation

on:
  push

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Documentation
        run: |
          python main.py --name_project "Automated Docs" --root_dir "./src" --ignore "['Readme_files', '__pycache__']" --languages "['en']" --parts 5

      - name: Upload Documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: README.md